### ISSUE TITLE
Synapse crashes on 'Start'

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/synapse-wrapper#19] opened 2021-11-30 04:51 UTC
![image](https://user-images.githubusercontent.com/39687477/143987665-75b4d3bf-4fa1-4efd-a811-f4a19a0a0a77.png)

Reported by: @kn0wmad

**Comment by chrisguida** [comment] 2021-11-30 12:06
Duplicate of https://github.com/Start9Labs/synapse-wrapper/issues/18, closing

**Closed** 2021-11-30 12:06 UTC
Labels: P1 - Blocks Release, Duplicate, Needs Scoping, Bug
